// All reusable variables here
#let myLang = "it"
#let myName = "Luca Ribon"
#let myMatricola = "2075516"
#let myTitle = "Migrazione al protocollo MQTT per un sistema di monitoraggio basato su dispositivi RFID"
#let myDegree = "Tesi di Laurea Triennale"
#let myUni = "Università degli Studi di Padova"
#let myDepartment = "Dipartimento di Matematica ''Tullio Levi-Civita''"
#let myFaculty = "Corso di Laurea in Informatica"
#let profTitle = "Prof. "
#let myProf = "Marco Zanella"
#let myCompany = "KanbanBOX S.r.l."
#let myTutor = "Nome Cognome"
#let myLocation = "Padova"
#let myAA = "2025-2026"
#let myTime = "Mese 2026"